### ISSUE TITLE
关于启动问题。（虚心请教）

### ISSUE THREAD

**Issue by luoqingfu** [Lemonzhulixin/python-appium#1]
直接clone 运行runner  
报：Exception: can't get packageinfo
是否需要其他步骤，

**Comment by Lemonzhulixin** [comment]
单独调试下BaseApk.py，打印下getApkBaseInfo输出的内容，可能是你的apk包格式与代码里不一致，打印出来看下，或者你提供下你们app的名称，我这边调试下看看。

**Comment by luoqingfu** [comment]
已经调试成功，需要修改：baseInit，app路径，以及logpath.txt中的路径
